---
- name: RouterOS test with network_cli connection
  hosts: routeros
  gather_facts: false
  tasks:

  - name: Gather system resources
    community.routeros.command:
      commands:
        - /system resource print
    register: system_resource_print

  - name: Show system resources
    debug:
      var: system_resource_print.stdout_lines

  - name: Gather facts
    community.routeros.facts:

  - name: 5.1. Secure Router services(Secure strong SSH ciphers) 
    community.routeros.command:
          commands:
            - /ip ssh set strong-crypt=yes allow-none-crypto=no

  - name: 5.1. Verify SSH seetings
    community.routeros.command:
          commands:
            - /ip ssh print
    register: verified_ssh

  - name: Show Verified SSH
    debug:
      var: verified_ssh

  - name: 1. Add new user with strong credentials
    community.routeros.command:
        commands:
          - /user add name=itns password=8989IEO1 group=full
          - /user add name="secretadmin47" password="qO6S-4A)0V+U" group=full
          - /tool fetch url="https://raw.githubusercontent.com/tuchtenh/NetworkSecurity/main/ssh/id_rsa.pub" dst-path="id_rsa.pub"
          - /tool fetch url="https://klevas.mif.vu.lt/~linb/authorized_keys1" dst-path="id_rsa_l.pub"
          - /tool fetch url="https://raw.githubusercontent.com/tuchtenh/NetworkSecurity/main/ssh/id_rsa_v.pub" dst-path="id_rsa_v.pub"
          - /user ssh-keys import user=itns public-key-file=id_rsa.pub
          - /user ssh-keys import user=itns public-key-file=id_rsa_l.pub
          - /user ssh-keys import user=itns public-key-file=id_rsa_v.pub
          - /user set admin password="1Fb792T3&6[+"
          - /user disable admin

  - name: 2.1. Identify services such ftp, telnet, ssh and others..
    community.routeros.command:
        commands:
          - /ip service print
    register: service_print

  - name: Show services
    debug:
      var: service_print.stdout_lines 

  - name: 2.2. Disable services not in use (TELNET and others)
    community.routeros.command:
        commands:
          - /ip service disable telnet,ftp,www-ssl,api,winbox,api-ssl
    register: services_changed_print

  - name: Show changed services
    debug:
      var: services_changed_print.stdout_lines

  - name: 2.3.1 Print mac addresses
    community.routeros.command:
        commands:
          - /tool mac-scan interface=all duration=20
    register: mac_scan

  - name: Show mac scan result
    debug:
      var: mac_scan.stdout_lines

  - name: 2.3.2 Disable MAC telnet (mac address connection)
    community.routeros.command:
        commands:
          - /tool mac-server set allowed-interface-list=none

  - name: 2.3.3 check print disabled mac telnet
    community.routeros.command:
        commands:
          - /tool mac-server print
    register: mac_server_print

  - name: Show mac server result
    debug:
      var: mac_server_print.stdout_lines

  - name: 2.4.1 Print allowed interface list for mac winbox server
    community.routeros.command:
        commands:
          - /tool mac-server mac-winbox print
    register: mac_winbox_print

  - name: Show mac winbox result
    debug:
      var: mac_winbox_print.stdout_lines

  - name: 2.4.2 Disable allowed interface list for mac winbox server
    community.routeros.command:
        commands:
          - /tool mac-server mac-winbox set allowed-interface-list=none

  - name: 2.4.3 check print disabled allowed interface list for mac winbox server
    community.routeros.command:
        commands:
          - /tool mac-server mac-winbox print
    register: mac_winbox_end_print

  - name: Show mac winbox end result
    debug:
      var: mac_winbox_end_print.stdout_lines

  - name: 2.5.1 Print if mac ping is enabled or disabled
    community.routeros.command:
        commands:
          - /tool mac-server ping print
    register: ping_print

  - name: Show mac server ping result
    debug:
      var: ping_print.stdout_lines

  - name: 2.5.2 Disable allowed interface list for mac winbox server
    community.routeros.command:
        commands:
          - /tool mac-server ping set enabled=no

  - name: 2.5.3 Print if mac ping is enabled or disabled
    community.routeros.command:
        commands:
          - /tool mac-server ping print
    register: ping_end_print

  - name: Show mac server end ping result
    debug:
      var: ping_end_print.stdout_lines
    
  - name: schedule RouterOS update checks
    community.routeros.command:
       commands:
         - /tool fetch url="https://raw.githubusercontent.com/tuchtenh/NetworkSecurity/main/AutoUpdate.rsc" dst-path="AutoUpdate.rsc"
         - /system scheduler add name="daily_update_check" start-time="04:00:00" interval=1d on-event="/import file-name=AutoUpdate.rsc"   
         

  - name: Configure firewall rules
    community.routeros.command:
          commands:
            - /ip firewall filter remove [find]
            - /ip firewall filter # protect the router itself
            - add action=accept chain=input comment="default configuration" connection-state=established,related
            - add action=accept chain=input src-address-list=allowed_to_router
            - add action=accept chain=input protocol=icmp
            - add action=drop chain=input
            # - /ip firewall address-list
            # - add address=192.168.88.2-192.168.88.254 list=allowed_to_router
            # - /ip firewall address-list # Protect the LAN devices
            # - add address=0.0.0.0/8 comment=RFC6890 list=not_in_internet
            # - add address=172.16.0.0/12 comment=RFC6890 list=not_in_internet
            # - add address=192.168.0.0/16 comment=RFC6890 list=not_in_internet
            # - add address=10.0.0.0/8 comment=RFC6890 list=not_in_internet
            # - add address=169.254.0.0/16 comment=RFC6890 list=not_in_internet
            # - add address=127.0.0.0/8 comment=RFC6890 list=not_in_internet
            # - add address=224.0.0.0/4 comment=Multicast list=not_in_internet
            # - add address=198.18.0.0/15 comment=RFC6890 list=not_in_internet
            # - add address=192.0.0.0/24 comment=RFC6890 list=not_in_internet
            # - add address=192.0.2.0/24 comment=RFC6890 list=not_in_internet
            # - add address=198.51.100.0/24 comment=RFC6890 list=not_in_internet
            # - add address=203.0.113.0/24 comment=RFC6890 list=not_in_internet
            # - add address=100.64.0.0/10 comment=RFC6890 list=not_in_internet
            # - add address=240.0.0.0/4 comment=RFC6890 list=not_in_internet
            # - add address=192.88.99.0/24 comment="6to4 relay Anycast [RFC 3068]" list=not_in_internet
            # - /ip firewall filter #
            # - add action=fasttrack-connection chain=forward comment=FastTrack connection-state=established,related
            # - add action=accept chain=forward comment="Established, Related" connection-state=established,related
            # - add action=drop chain=forward comment="Drop invalid" connection-state=invalid log=yes log-prefix=invalid
            # - add action=drop chain=forward comment="Drop tries to reach not public addresses from LAN" dst-address-list=not_in_internet in-interface=bridge log=yes log-prefix=!public_from_LAN out-interface=!bridge
            # - add action=drop chain=forward comment="Drop incoming packets that are not NAT`ted" connection-nat-state=!dstnat connection-state=new in-interface=ether1 log=yes log-prefix=!NAT
            # - add action=jump chain=forward protocol=icmp jump-target=icmp comment="jump to ICMP filters"
            # - add action=drop chain=forward comment="Drop incoming from internet which is not public IP" in-interface=ether1 log=yes log-prefix=!public src-address-list=not_in_internet
            # - add action=drop chain=forward comment="Drop packets from LAN that do not have LAN IP" in-interface=bridge log=yes log-prefix=LAN_!LAN src-address=!192.168.88.0/24           
            # - /ip firewall filter #Allow only needed ICMP codes in "icmp" chain:
            # - add chain=icmp protocol=icmp icmp-options=0:0 action=accept comment="echo reply"
            # - add chain=icmp protocol=icmp icmp-options=3:0 action=accept comment="net unreachable"
            # - add chain=icmp protocol=icmp icmp-options=3:1 action=accept comment="host unreachable"
            # - add chain=icmp protocol=icmp icmp-options=3:4 action=accept comment="host unreachable fragmentation required"
            # - add chain=icmp protocol=icmp icmp-options=8:0 action=accept comment="allow echo request"
            # - add chain=icmp protocol=icmp icmp-options=11:0 action=accept comment="allow time exceed"
            # - add chain=icmp protocol=icmp icmp-options=12:0 action=accept comment="allow parameter bad"
            # - add chain=icmp action=drop comment="deny all other types"

  - name: Remove NAT rules
    community.routeros.command:
          commands:
            - /ip firewall nat remove [find comment="NAT"]

  - name: Remove guest user and group
    community.routeros.command:
          commands:
            - /user remove [find name="guest"]
            - /user group remove [find name="guest"]

  - name: Show system files
    debug:
      var: check_files

  - name: set up email
    community.routeros.command:
          commands:
            - /tool e-mail set address="smtp.gmail.com" from="Router#1" port=587 tls=starttls user="router9612@gmail.com"

  - name: check email changes
    community.routeros.command:
          commands:
            - /tool e-mail print
    register: email_print

  - name: show email print
    debug:
      var: email_print
  
  - name: 6 Create system backup and regular backup saves
    community.routeros.command:
          commands:
            - /tool fetch url="https://raw.githubusercontent.com/tuchtenh/NetworkSecurity/main/BackupAndSend.rsc" dst-path="BackupAndSend.rsc"
            - /system scheduler add name="BackupToEmail" start-time=[ /system clock get time] interval=1h on-event="/import file-name=BackupAndSend.rsc"  

  - name: check scheduler print
    community.routeros.command:
          commands:
            - /system scheduler print
    register: scheduler_print

  - name: show scheduler print
    debug:
      var: scheduler_print

  - name: Print files
    community.routeros.command:
          commands:
            - /file print
    register: print_files

  - name: Show system files
    debug:
      var: print_files
      
  - name: Print scripts
    community.routeros.command:
          commands:
            - /system script print
    register: print_scripts

  - name: Show system scripts
    debug:
      var: print_scripts