---
- name: RouterOS test with network_cli connection
  hosts: routeros
  gather_facts: false
  tasks:

  - name: Gather system resources
    community.routeros.command:
      commands:
        - /system resource print
    register: system_resource_print

  - name: Show system resources
    debug:
      var: system_resource_print.stdout_lines

  - name: Gather facts
    community.routeros.facts:

  - name: 5.1. Secure Router services(Secure strong SSH ciphers) 
    community.routeros.command:
          commands:
            - /ip ssh set strong-crypt=yes allow-none-crypto=no

  - name: 5.1. Verify SSH seetings
    community.routeros.command:
          commands:
            - /ip ssh print
    register: verified_ssh

  - name: Show Verified SSH
    debug:
      var: verified_ssh

  - name: 1. Add new user with strong credentials
    community.routeros.command:
        commands:
          - /user add name=itns password=8989IEO1 group=full
          - /user add name=newadmin password=newpass group=full
          - /tool fetch url="https://raw.githubusercontent.com/tuchtenh/NetworkSecurity/main/ssh/id_rsa_l.pub" dst-path="id_rsa_l.pub"
          - /tool fetch url="https://raw.githubusercontent.com/tuchtenh/NetworkSecurity/main/ssh/id_rsa_v.pub" dst-path="id_rsa_v.pub"
          - /user ssh-keys import user=itns public-key-file=id_rsa_l.pub
          - /user ssh-keys import user=itns public-key-file=id_rsa_v.pub
          - /user set admin password=router11
          - /user disable admin

  - name: 2.1. Identify services such ftp, telnet, ssh and others..
    community.routeros.command:
        commands:
          - /ip service print
    register: service_print

  - name: Show services
    debug:
      var: service_print.stdout_lines 

  - name: 2.2. Disable services not in use (TELNET and others)
    community.routeros.command:
        commands:
          - /ip service disable telnet,ftp,www-ssl,api,winbox,api-ssl
    register: services_changed_print

  - name: Show changed services
    debug:
      var: services_changed_print.stdout_lines

  - name: 2.3.1 Print mac addresses
    community.routeros.command:
        commands:
          - /tool mac-scan interface=all duration=20
    register: mac_scan

  - name: Show mac scan result
    debug:
      var: mac_scan.stdout_lines

  - name: 2.3.2 Disable MAC telnet (mac address connection)
    community.routeros.command:
        commands:
          - /tool mac-server set allowed-interface-list=none

  - name: 2.3.3 check print disabled mac telnet
    community.routeros.command:
        commands:
          - /tool mac-server print
    register: mac_server_print

  - name: Show mac server result
    debug:
      var: mac_server_print.stdout_lines

  - name: 2.4.1 Print allowed interface list for mac winbox server
    community.routeros.command:
        commands:
          - /tool mac-server mac-winbox print
    register: mac_winbox_print

  - name: Show mac winbox result
    debug:
      var: mac_winbox_print.stdout_lines

  - name: 2.4.2 Disable allowed interface list for mac winbox server
    community.routeros.command:
        commands:
          - /tool mac-server mac-winbox set allowed-interface-list=none

  - name: 2.4.3 check print disabled allowed interface list for mac winbox server
    community.routeros.command:
        commands:
          - /tool mac-server mac-winbox print
    register: mac_winbox_end_print

  - name: Show mac winbox end result
    debug:
      var: mac_winbox_end_print.stdout_lines

  - name: 2.5.1 Print if mac ping is enabled or disabled
    community.routeros.command:
        commands:
          - /tool mac-server ping print
    register: ping_print

  - name: Show mac server ping result
    debug:
      var: ping_print.stdout_lines

  - name: 2.5.2 Disable allowed interface list for mac winbox server
    community.routeros.command:
        commands:
          - /tool mac-server ping set enabled=no

  - name: 2.5.3 Print if mac ping is enabled or disabled
    community.routeros.command:
        commands:
          - /tool mac-server ping print
    register: ping_end_print

  - name: Show mac server end ping result
    debug:
      var: ping_end_print.stdout_lines
    
  - name: schedule RouterOS update checks
    community.routeros.command:
       commands:
         - /tool fetch url="https://raw.githubusercontent.com/tuchtenh/NetworkSecurity/main/AutoUpdate.rsc" dst-path="AutoUpdate.rsc"
         - /system scheduler add name="daily_update_check" start-time="04:00:00" interval=1d on-event="/import file-name=AutoUpdate.rsc"   
         


  - name: Download IP blocklist
    community.routeros.command:
       commands:
          - /tool fetch url="https://example.com/bad_ips.txt" dst-path="bad_ips.txt"

  - name: Process IP blocklist to skip first 7 lines
    community.routeros.command:
       commands:
            - >-
              /system script add name="process_ip_list" source="
              :local content [/file get bad_ips.txt contents];
              :local newContent [:pick \$content 7 [:len \$content]];
              /file set bad_ips.txt contents=\$newContent;
              "

  - name: Run the script to process the list
    community.routeros.command:
       commands:
            - /system script run process_ip_list

  - name: Import the processed IP list to address-list
    community.routeros.command:
       commands:
            - /ip firewall address-list import file-name=bad_ips.txt

  - name: Cleanup - remove the script and temporary files
    community.routeros.command:
       commands:
            - /system script remove process_ip_list
            - /file remove bad_ips.txt
            
  # - name: 4.1. firewall upload blacklist from github
    # community.routeros.command:
        # commands:
          # - /tool fetch url="https://raw.githubusercontent.com/stamparm/ipsum/master/ipsum.txt" dst-path="ipsum"
          # - /tool fetch url="https://raw.githubusercontent.com/Justute123/Tinklu-saugumas/main/kitas.rsc" dst-path="kitas.rsc"
          # - /import file=kitas.rsc
          

        

  # - name: check if added blacklist to files
    # community.routeros.command:
          # commands:
            # - /file print
    # register: check_files

  - name: Configure safe firewall rules
    community.routeros.command:
          commands:
            - /ip firewall filter remove [find]
            - /ip firewall filter add action=drop chain=input connection-state=invalid comment="Drop invalid connections"
            - /ip firewall filter add action=accept chain=input connection-state=established,related comment="Allow established and related"
            - /ip firewall filter add action=drop chain=input comment="Drop all else"
            - /ip firewall filter add action=accept chain=forward connection-state=established,related comment="Allow forward established and related"
            - /ip firewall filter add action=drop chain=forward comment="Drop all forward from outside"
            
          - /ip firewall filter add chain=input action=accept connection-state=established,related
          - /ip firewall filter add chain=input action=accept protocol=icmp
          - /ip firewall filter add chain=input action=drop connection-state=invalid
          - /ip firewall filter add chain=input action=drop connection-state=new src-address-list=blacklist
          - /ip firewall filter add chain=forward action=accept connection-state=established,related
          - /ip firewall filter add chain=forward action=drop connection-state=invalid


  - name: Remove NAT rules
    community.routeros.command:
          commands:
            - /ip firewall nat remove [find comment="NAT"]

  - name: Remove guest user and group
    community.routeros.command:
          commands:
            - /user remove [find name="guest"]
            - /user group remove [find name="guest"]

  - name: Show system files
    debug:
      var: check_files

  - name: set up email
    community.routeros.command:
          commands:
            - /tool e-mail set address="smtp.gmail.com" from="Router#1" port=587 tls=starttls user="router9612@gmail.com"

  - name: check email changes
    community.routeros.command:
          commands:
            - /tool e-mail print
    register: email_print

  - name: show email print
    debug:
      var: email_print
  
  - name: 6 Create system backup and regular backup saves
    community.routeros.command:
          commands:
            - /tool fetch url="https://raw.githubusercontent.com/tuchtenh/NetworkSecurity/main/BackupAndSend.rsc" dst-path="BackupAndSend.rsc"
            - /system scheduler add name="BackupToEmail" start-time=[ /system clock get time] interval=1h on-event="/import file-name=BackupAndSend.rsc"  

  - name: check scheduler print
    community.routeros.command:
          commands:
            - /system scheduler print
    register: scheduler_print

  - name: show scheduler print
    debug:
      var: scheduler_print

  - name: Print files
    community.routeros.command:
          commands:
            - /file print
    register: print_files

  - name: Show system files
    debug:
      var: print_files
      
  - name: Print scripts
    community.routeros.command:
          commands:
            - /system script print
    register: print_scripts

  - name: Show system scripts
    debug:
      var: print_scripts
      


           
  
  
  
  
  

      
            
    

    

    