---
- name: RouterOS test with network_cli connection
  hosts: routeros
  gather_facts: false
  tasks:

  - name: Gather system resources
    community.routeros.command:
      commands:
        - /system resource print
    register: system_resource_print

  - name: Show system resources
    debug:
      var: system_resource_print.stdout_lines

  - name: Gather facts
    community.routeros.facts:

  - name: enable ssh strong-crypt
    community.routeros.command:
        commands:
          - /ip ssh set strong-crypt=yes allow-none-crypto=no

  - name: 1. Add new user with strong credentials
    community.routeros.command:
        commands:
          -/user add name=newadmin password=newpass group=full

  - name: 2.1. Identify services such ftp, telnet, ssh and others..
    community.routeros.command:
        commands:
          - /ip service print
    register: service_print

  - name: Show services
    debug:
      var: service_print.stdout_lines 

  - name: 2.2. Disable services not in use (TELNET and others)
    community.routeros.command:
        commands:
          -/ip service disable telnet,ftp,www-ssl,api,winbox,api-ssl
    register: services_changed_print

  - name: Show changed services
    debug:
      var: servicechanged_print.stdout_lines

   # - name: 5.2. Enforce secure protocols  FTPS(a secure way for uploading ssh key to localhost...) AND HTTPS ????????????????????
    # community.routeros.command:
          # commands:
            # # - /ip service set ftps disabled=no
            # - /ip service set www-ssl disabled=no

  - name: 1. upload ssh to files and import it ???????
    community.routeros.command:
        commands:
          # sitas nesuveiks
          #- /tool fetch url="ftps://localhost:8080/" user="newadmin password="newpass" mode=ftps upload=yes scr-path="/home/jugr5805/.ssh/id_rsa.pub" dst=path="/webfig/#Files"
          #- /user ssh-keys import user="newadmin public-key-file=id_rsa.pub
 
  - name: 2.3.1 Print mac addresses
    community.routeros.command:
        commands:
          - /tool mac-scan interface=all duration=20
    register: mac_scan

  - name: Show mac scan result
    debug:
      var: mac_scan.stdout_lines

  - name: 2.3.2 Disable MAC telnet (mac address connection)
    community.routeros.command:
        commands:
          - /tool mac-server set allowed-interface-list=none

  - name: 2.3.3 check print disabled mac telnet
    community.routeros.command:
        commands:
          - /tool mac-server print
    register: mac_server_print

  - name: Show mac server result
    debug:
      var: mac_server_print.stdout_lines

  - name: 2.4.1 Print allowed interface list for mac winbox server
    community.routeros.command:
        commands:
          - /tool mac-server mac-winbox print
    register: mac_winbox_print

  - name: Show mac winbox result
    debug:
      var: mac_winbox_print.stdout_lines

  - name: 2.4.2 Disable allowed interface list for mac winbox server
    community.routeros.command:
        commands:
          - /tool mac-server mac-winbox set allowed-interface-list=none

  - name: 2.4.3 check print disabled allowed interface list for mac winbox server
    community.routeros.command:
        commands:
          - /tool mac-server mac-winbox print
    register: mac_winbox_end_print

  - name: Show mac winbox end result
    debug:
      var: mac_winbox_end_print.stdout_lines

  - name: 2.5.1 Print if mac ping is enabled or disabled
    community.routeros.command:
        commands:
          - /tool mac-server ping print
    register: ping_print

  - name: Show mac server ping result
    debug:
      var: ping_print.stdout_lines

  - name: 2.5.2 Disable allowed interface list for mac winbox server
    community.routeros.command:
        commands:
          - /tool mac-server ping set enabled=no

  - name: 2.5.3 Print if mac ping is enabled or disabled
    community.routeros.command:
        commands:
          - /tool mac-server ping print
    register: ping_end_print

  - name: Show mac server end ping result
    debug:
      var: ping_end_print.stdout_lines

  # - name: 3.1. Check for RouterOS updates
    # community.routeros.command:
        # commands:
          # - /system package update check-for-updates
    # register: system_update_print

  # - name: Show RouterOs updates
    # debug:
      # var: system_update_print.stdout_lines

  # - name: 3.2. Update RouterOS version
    # community.routeros.command:
        # commands:
          # - /system package update install
    # when: system_update_print is not search('System is already up to date')

  #sitas turetu tikriausiai pradzioj buti po susikurimo userio.
  - name: 5.1. Secure Router services(Secure strong SSH ciphers) 
    community.routeros.command:
          commands:
            - /ip ssh set strong-crypt=yes allow-none-crypto=no

  - name: 5.1. Verify SSH seetings
    community.routeros.command:
          commands:
            - /ip ssh print
    register: verified_ssh

  - name: Show Verified SSH
    debug:
      var: verified_ssh

  - name: 4.1. firewall upload blacklist from github
    community.routeros.command:
        commands:
          - /tool fetch url="https://raw.githubusercontent.com/stamparm/ipsum/master/ipsum.txt" dst-path="webfig/#Files"
          - /tool fetch url="https://github.com/Justute123/Tinklu-saugumas/blob/main/kitas.rsc" dst-path="kitas.rsc"
          - /import file=kitas.rsc
        

  - name: check if added blacklist to files
    community.routeros.command:
          commands:
            - /file print
    register: check_files

  - name: Show system files
    debug:
      var: check_files

  
  - name: 6 Create system backup and regular backup saves
    community.routeros.command:
          commands:
            - /system backup save name=backup password="router1"
            - /system scheduler add name=backupschedulerbackup interval=1h start-time=[ /system clock get time] on-event=backUP
            - /system scheduler print  

  - name: Print files
    community.routeros.command:
          commands:
            - /file print
    register: print_files

  - name: Show system files
    debug:
      var: print_files
      


           
  
  
  
  
  

      
            
    

    

    