---
- hosts: routeros
  gather_facts: false
  tasks:
    - name: 1. Add new user with strong credentials
      community.routeros.command:
        commands:
          -/user add name=newadmin password=newpass group=full
#          -/user remove admin
    - name: 2.1. Identify services such ftp, telnet, ssh and others..
      community.routeros.command:
        commands:
          -/ip service print
    - name: 2.2. Disable services not in use
      community.routeros.command:
        commands:
          -/ip service disable telnet,ftp,www-ssl,api,winbox,api-ssl
    - name: 2.3. Validate changes
      community.routeros.command:
        commands:
          -/ip service print

    # - name: 2.3.1 Print mac addresses
      # community.routeros.command:
        # commands:
          # -/tool mac-scan interface=all  

    - name: 2.3.2 Disable MAC telnet (mac address connection)
      community.routeros.command:
        commands:
          -/tool mac-server set allowed-interface-list=none

    - name: 2.3.3 check print disabled mac telnet  
      community.routeros.command:
        commands:
          -/tool mac-server print

    - name: 2.4.1 Print allowed interface list for mac winbox server
      community.routeros.command:
        commands:
          -/tool mac-server mac-winbox print 

    - name: 2.4.2 Disable allowed interface list for mac winbox server
      community.routeros.command:
        commands:
          -/tool mac-server mac-winbox set allowed-interface-list=none

    - name: 2.4.3 check print disabled allowed interface list for mac winbox server 
      community.routeros.command:
        commands:
          -/tool mac-server mac-winbox print 

    - name: 2.5.1 Print if mac ping is enabled or disabled
      community.routeros.command:
        commands:
          -/tool mac-server ping print 

    - name: 2.5.2 Disable allowed interface list for mac winbox server
      community.routeros.command:
        commands:
          -/tool mac-server ping set enabled=no 

    - name: 2.5.3 Print if mac ping is enabled or disabled
      community.routeros.command:
        commands:
          -/tool mac-server ping print 

    # - name: 3.1. Check for RouterOS updates
      # community.routeros.command:
        # commands:
          # - /system package update check-for-updates
      # register: system_update_print

    # - name: 3.2. Update RouterOS version
      # community.routeros.command:
        # commands:
          # - /system package update install
      # when: system_update_print is not search('System is already up to date')

    # - name: 4.1 Import blacklist for firewall
      # community.routeros.command:
        # commands:
          # - /tool fetch address=https://raw.githubusercontent.com/stamparm/ipsum/master/ipsum.txt mode=http src-path=/downloads/ipsum.txt :delay 10
          # - /import ipsum.txt

    # - name: 4.2 add Ip's to blaclist line by line
      # community.routeros.command:
        # commands: 
          # # neaisku koks mikrotik tik extension turetu buti skrito failo, kad runnintu
          # - /tool fetch address="scripto adresas is github tarkim vadinasi readIp" mode=http src-path=/downloads/readIp :delay 10
          # - /import readIp
          # - /system script run readIp

    # - name: 4.3 add firewall rules
      # community.routeros.command:
         # commands:
         # #Router and internal network protection, no internal servers, LAN is friendly
         # - /add chain=input   action=drop   connection-state=invalid log=yes                 comment="Disallow weird packets" 
         # - /add chain=input   action=accept connection-state=new         in-interface=LAN    comment="Allow LAN access to router and Internet"
         # - /add chain=input   action=accept connection-state=established                     comment="Allow connections that originated from LAN"
         # - /add chain=input   action=accept connection-state=related                         comment="Allow connections that originated from LAN"
         # - /add chain=input   action=accept protocol=icmp                                    comment="Allow ping ICMP from anywhere"
         # - / add chain=input dst-address-list=blacklist log=yes action=drop                  comment="Disallow ips from blacklist"
         # - /add chain=forward action=drop   connection-state=invalid                         comment="Disallow weird packets" 
         # - /add chain=forward action=accept connection-state=new         in-interface=LAN    comment="Allow LAN access to router and Internet"
         # - /add chain=forward action=accept connection-state=established                     comment="Allow connections that originated from LAN"
         # - /add chain=forward action=accept connection-state=related                         comment="Allow connections that originated from LAN"               
         # - / add chain=forwad dst-address-list=blacklist log=yes action=drop                 comment="Disallow ips from blacklist"
    
   

      